services:
  little-load-tracker-db:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./container-data/potgresql/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  little-load-tracker-cache-database:
    image: redis:7.4.2-alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./container-data/redis/data:/data