export const SOCKET_EVENTS = {
	LOADS: {
		CREATE_LOAD: "CREATE_LOAD",
		UPDATE_LOAD: "UPDATE_LOAD",
		DELETE_LOAD: "DELETE_LOAD",
	},
	ITEMS: {
		CREATE_ITEM: "CREATE_ITEM",
		UPDATE_ITEM: "UPDATE_ITEM",
		DELETE_ITEM: "DELETE_ITEM",
	},
}
